### ISSUE TITLE
Laravel 5.5 textlocal Sms

### ISSUE THREAD

**Issue by cnuvasan** [msonowal/textlocal#1]
I have a issue that the code doesnot work in laravel 5.5.
So If the code is in the same in laravel 5.5 with textlocal sms i may helpful for me

**Comment by msonowal** [comment]
what is the error @cnuvasan ?

**Comment by msonowal** [comment]
Check this commit 980183cef0e060c9b441bde62c152fa62eb03873

**Comment by cnuvasan** [comment]
Fine i am new for the php and laravel, but now i am familiar with laravel5.5. i got confusing on installing the code, in ubuntu composer install is not working on updating the packages. please make in try with laravel 5.5

**Comment by msonowal** [comment]
@cnuvasan Please follow the readme once step by step and tell me what is the issue

**Comment by cnuvasan** [comment]
I got a error I the first command. Kindly try in laravel 5.5 . This is the exact error I got it in earlier in Ubuntu

**Comment by cnuvasan** [comment]
Give me some reply

**Comment by Varin6** [comment]
@cnuvasan Entitled much? He asked you to give ANY details about the error, and you just keep saying that there is an error. In order to debug anything, he's got to have some, even minimal info.

**Comment by msonowal** [comment]
Project has been moved to 
https://github.com/msonowal/laravel-notification-channel-textlocal
